### ISSUE TITLE
Kompatibilitaet mit anderen Templates (z.B. Mosaic)

### ISSUE THREAD

**Issue by lisandi** [typo3-themes/theme_bootstrap_highland#4] opened 2015-09-10 16:34 UTC
Ich habe heute die beiden Templates (Highland und Mosaic)<RTE Type Dropdown Mosaic.png><RTE Type Dropdown Highland.png> einmal ausprobiert und festgestellt dass im RTE die Type Layouts nicht kompatibel miteinander sind.

der eine zeigt Highland der andere Mosaic

Wenn die nicht kompatibel sind dann kann man die Templates nicht untereinander austauschen bzw. switchen 

In Highland sind Layout 1 = H1 -> Layout 5 = H5
In Highland sind Layout 1 = H3 und dann sehr unlogisch bis Layout 5 etc angeordnet.

Es scheint auch das h4 gleich zweimal vorkommt 
<img width="283" alt="screen shot 2015-09-10 at 11 32 13 pm" src="https://cloud.githubusercontent.com/assets/1982011/9794254/404110fc-5814-11e5-9b34-8ebb0428ce3f.png">
<img width="280" alt="screen shot 2015-09-10 at 11 32 32 pm" src="https://cloud.githubusercontent.com/assets/1982011/9794261/48d9934c-5814-11e5-8e04-0474fe057f9e.png">

ist das Absicht, oder einfach ein "bug" der Kompatibilitaet.

Ansonsten sehr gute Arbeit die ihr da geleistet habt.
<img width="170" alt="rte type dropdown highland" src="https://cloud.githubusercontent.com/assets/1982011/9794110/7f5af1fa-5813-11e5-83ef-7f513f96a80c.png">
<img width="202" alt="rte type dropdown mosaic" src="https://cloud.githubusercontent.com/assets/1982011/9794111/7fae62b8-5813-11e5-80cb-418461511ca6.png">

**Comment by kaystrobach** [comment] 2015-09-13 17:14
hi @lisandi please lets switch to english to make it easy for others to follow.

basicly yes, this is intended behaviour, instead of forcing all into a totally scary corset, we just defined the datastructures, which make the switch possible without loosing content.

But it maybe the case, that some themes offer options which others do not offer.

As modern frameworks have special needs sometimes, themes can stick more or less to the standard. F.e some themes have 10 types of h3's which was not possible with other frameworks before.

/cc @Bunnyfield @tdeuling

**Comment by kaystrobach** [comment] 2015-09-13 17:17
just to mention the zurbink themes currently disables the rendering of the default theme grids in the part of the pagetree if selected.

https://github.com/typo3-themes/theme_zurbink

This is also intended, because this theme has a special purpose - sending mails - and i had limited time / money to implement it ...

**Comment by lisandi** [comment] 2015-09-14 07:37
IMHO it would be important to have at least the basic headers h1 - h3 on
the same spot and with the same namings.

Every site has h1 , h2 and h3

If now the default in some sites is h2 but in others h1 it does not make
sense as you won;t be able to switch a theme if you ever used "default"
settings what is usually the case. So default should be h2 in all templates.

The point is actually the namings.
Default = Standard h2
Layout 1 = h1 would be logical correct and easy to understand
Layout 2 = h2 (i.e. with a different style as h2 is already used in default)
Layout 3 = h3
Layout 4
Layout 5
Hidden
Layout 6
Layout 7

This is how it should look at least in every Template, what ever other
styles and Designs, sizes come in on Layout 4 - Layout 7 could be more
flexible

A horizontal line setting could be done also with frames!

Layout 6 and Layout 7 as they are listed behind the "Hidden" could be the
Feature styles like done in some Templates
Layout 4 and Layout 5 could be the h3 settings you mentioned kay

It doesn't make sense to name thise styles always in a different way Layout
1 - Layout 3

If you have to change all your h2 headers in your site again back to h2
because a new template is using now h1 or h3 or whats however is additional
work which is simply waste of time.

i.e. what would we do with those templates which ar inhomogene in those
settings. we would simply have to release them again with the IMHO correct
settings! which would cause doubled extensions in TER and SKIN repositories.

How many headers could be defined in TYPO3?
Probably there is a way to define more than 7.

The biggest benefit of the Templates for Framework for TemplaVoila is and
was that those styles were interchangeable and did not cause any strange
looks on major headlines.

Unfortunately exactly this is the case when you switch from highland to
mosaic or vice versa.

If those templates should be only DEVELOPER Tools than the intention to
make it difficult for regular Admins and users to switch a Theme would be
useful but to make people happy it would be to keep a standard in the basic
settings in a logical and easy to remembered order!

**Comment by kaystrobach** [comment] 2015-09-14 07:41
it makes sense, if one layout has a global h1 on every page (defined in layout) and another one not.

as h's are use for structuring content this is totally fine.
And this was also possible with TVF ...

frames is deprecated

**Comment by lisandi** [comment] 2015-09-17 08:44
switching Themes will lead that way to a mass!

i.e.

http://t3.thaipo3.com/customizing/ with Highland Theme

http://t0.thaipo3.com/customizing/ with Mosaic Theme

On those pages are no special content stuff and both are using the same
Header settings.

http://t3.thaipo3.com/headers/ Highland which is using Layout 1 with h1
and
http://t0.thaipo3.com/headers/ Mosaic which is using Layout 1 with h3

IMHO to make the best user experience of Themes those settings should be
identical and interchangeable without such major design problems.
Concerning the namings it would be useful to use the RTE Namings (Header 3)
instead of (Layout 1) etc.

Like said before there should be a standard part and a flexible part but
the standard part should focus on interchangeable operations of those
templates as otherwise it does not make sense to use THEMES if you have to
change all settings only because you changed a Theme.

If this is not intended in future and if that should stay like right now
(no standards for Layouts / Headers) please let us know. as we than would
change those settings, so that they are interchangeable for the new WEC
like Packages. Thanks.

With kind regards,
Mit freundlichen Grüßen,
Con un cordial saludo,
Cordialement,
с сердечным приветом,
เรื่องที่เกี่ยวกับชนิด,
與親切的問候,

_ANDI BECKER_

CEO/General Manager LisAndi Co., Ltd.

_--------------------------------------------------_
_LisAndi Co. Ltd._, Phuket, Thailand (lisandi.com)
15/21 M.2 Viset Road, Rawai, Muang, Phuket, Thailand 83130

Mobile: +66 (0)81 606 3378
VoIP:   +49 (0)711 50 88788 50
Fax:     +49 (0)711 50 88788 50
Skype:          lisandi
Facebook:     andibecker
Google Talk:  andi@lisandi.com
Facetime:      andi@lisandi.com

---

This email may contain confidential and/or privileged information. If you
are not the intended recipient (or have received this email by mistake),
please notify the sender immediately and destroy this email. Any
unauthorized copying, disclosure or distribution of the material in this
email is strictly prohibited. Email transmission security and error-free
status cannot be guaranteed as information could be intercepted, corrupted,
destroyed, delayed, incomplete, or contain viruses. The sender therefore
does not accept liability for any errors or omissions in the contents of
this message which may arise as a result of email transmission

**Comment by Bunnyfield** [comment] 2015-09-17 09:55
Theme developers are completely free to choose how much they would like to stick to certain standards or if they prefer to go a different way. The point is that THEMES just tries to guarantee that no content will be completely lost when changing a theme and that classes that trigger a certain behaviour will be still working. There is no guarantee for completely interchangeable content though. So if you feel it is important to take care of headers and RTE settings to be identical in different themes, feel free to do so in the themes you are going to create.

**Comment by kaystrobach** [comment] 2015-09-17 10:09
:+1: would like to see your concept for highly diverging themes like zurbink and f.e. mosaic then ;)

**Comment by lisandi** [comment] 2015-09-17 15:32
It is actually not much changing ;-)

we only change the settings to the right place - nothing more and nothing
less.

Every THEME has a

h1
h2
h3
h4

and sometimes more or even variations of it.

Take the examples I posted.

In Highland Layout 1  is named layout 1 and it is taking h1

In Mosaic Layout 1 had been renamed and explained much better actually what
it is and it is h3

It are those two simple differences which make things unnecessarily
complicated!

As both templates are using the correct Header settings in RTE Heading 1 -
Heading 6 h1 - h6 it would simply be useful to do the same for the Headings
of the Content Elements - which unfortunately are named Layout 1 - Layout xx

Our idea is to take the exact same templates and simply changing the
settings in Highland!

so that

Default is h2 - Heading 2 in RTE will be a variation but also h2 (without
Line)
Layout 1 will be renamed to Heading 3.1 (i.e. h3 + it has a line) - Heading
3 will be h3 but in a variation
Layout 2 will be renamed to Heading 3.2 (i.e. another variation)
Layout 3 will be renamed to Heading 4.1 - in RTE it will be Heading 4 h4 in
a variation which is suitable to write longer texts without always the need
to create a new CE because you want to repeat the header settings
Layout 4 will be renamed to Heading 4.2
Layout 5 will be the separator Line - useful when you want to split
articles but don't have a new header
Hidden (self explanatory)
Layout 6 will be settings for Heading 1.1 like it is done in Mosaic
Layout 7 will be settings for Heading 1.2 like it is done in Mosaic
in RTE Heading 1 will be h1

as in Highland the setting is Layout 1 = h1 this would be changed to be
like described above.

As a result you would be able to interchange the templates like it is
possible also in Framework for TemplaVoila, without that your Major text
Layout is breaking the sites!

A Theme Switcher could be used easily to display all those templates like
it has been done with the Theme Switcher of the WEC!

Frontend Users could access a Site full of Demo Content and could simply
switch all those Themes until they have found the one theme they would like
to start with.

As those headers are used also to structure the text - which is also good
for SEO and Visibility - usually there should be not a gap in using the
headers. i.e. h1 and than h4 and perhaps h6. Better would be h1 (one time
on the page - pagetitle, or special title) h2 for Headlines on the pages
(i.e. for article Main headers) h3 (for sub Headlines) etc and than h4
(i.e. for headlines inside ce's)

It is as you see not a problem of so many different settings like mosaic or
whats however is offering, it is simply and only the correct start to use
the correct settings for major header settings h1, h2, h3, h4 and
horizontal Line/Separator (as Frames is deprecated) and accordingly Header
1 - Header 4 in RTE settings in all new THEMES in the same way. Everything
what is than something special can be placed i.e. in Layout 6 and Layout 7
and Heading 5, 6, ... in RTE. This would increase the usability of THEMES
tremendously

"would like to see your concept for highly diverging themes like zurbink
and f.e. mosaic then ;)"

The concept is a very simple one - keep it Simple and Logical - all the

## diverging stuff can than be placed in the rest of the settings.

Check again the Example links I have posted - Everything is actually fine
and nice looking in Mosaic Theme but it looks horrible in Highland. The
reason is that we used the logical settings of Mosaic with

Default = h2
Layout 1 = h3
Layout 2 = h4

when we entered the content.

We tried it also the other way around but than realized that it is complete
unlogical to have more than one h1 header on a Page and that therefore it
is also unlogical to have settings like

Default = h2
Layout 1 = h1
Layout 2 = h3
Layout 3 = h4

For editors it is much much easier to simply not have the option to set h1
right the way after default h2 - h1 - h3
The Mosaic way is therefore the much better way in having it as h2 - h3 -
h4  in a logical order, which will improve the workflow of an editor.

When this is done all the additional diversity settings could be integrated
if this is at all possible in TYPO3 as there are only Layout 1 - 7 right
now!

zurbink is right now not in any discussion here as we concentrate 100% on
bootstrap!

"There is no guarantee for completely interchangeable content though"

I disagree in that concerning the major h1 - h4 settings of ANY page which
is properly build according to common standards!

With kind regards,
Mit freundlichen Grüßen,
Con un cordial saludo,
Cordialement,
с сердечным приветом,
เรื่องที่เกี่ยวกับชนิด,
與親切的問候,

_ANDI BECKER_

CEO/General Manager LisAndi Co., Ltd.

_--------------------------------------------------_
_LisAndi Co. Ltd._, Phuket, Thailand (lisandi.com)
15/21 M.2 Viset Road, Rawai, Muang, Phuket, Thailand 83130

Mobile: +66 (0)81 606 3378
VoIP:   +49 (0)711 50 88788 50
Fax:     +49 (0)711 50 88788 50
Skype:          lisandi
Facebook:     andibecker
Google Talk:  andi@lisandi.com
Facetime:      andi@lisandi.com

---

This email may contain confidential and/or privileged information. If you
are not the intended recipient (or have received this email by mistake),
please notify the sender immediately and destroy this email. Any
unauthorized copying, disclosure or distribution of the material in this
email is strictly prohibited. Email transmission security and error-free
status cannot be guaranteed as information could be intercepted, corrupted,
destroyed, delayed, incomplete, or contain viruses. The sender therefore
does not accept liability for any errors or omissions in the contents of
this message which may arise as a result of email transmission

**Comment by kaystrobach** [comment] 2015-09-18 06:30
Hi Andreas, as you told here and before you seam to have enough man power to create quite some themes. There are 2 opposite requests in our community.
- be flexible do not loose content, but maybe one or two settings
- make a walled garden and restrict things, to get even better switch ability and optimize to that point

You can help defining your walled garden by providing real open source themes via our platform. If the community wants that the THEMES team can discuss to have that as suggestion in the compatibility guide.

But changing current mosaic and highland will break existing customer projects, so I do not see a value there ...

Looking forward to see your work

Chears

**Comment by lisandi** [comment] 2015-09-18 07:11
Hi kay this is absolutely no problem for us as we will in that case simply
change the current existing themes to the settings which would be
interchangeable and would need to release them again as lets say
interchangeable Themes. This is not a big deal at all as only the Layout
settings need to be switched actually.

We won't do much changes as far as I can see on Mosaic as here the
developer thought first and acted than - They provide already a logical
structure mostly.

The big plus in Framework for TemplaVoila is still that you can interchange
any template with another and your major header settings will stay the
same. We just adjusted here all Themes to make them work in 6.2.15 with the
newest Version of Framework for TemplaVoila which isn't unfortunately only
available from git right now.

To have the same settings like discussed years ago with you especially for
our multidomain sites which get managed with the sitemanager, it is simply
necessary to have interchangeable Themes.

The same would be necessary if you will provide some kind of TYPO3
"Hosting" where you offer also other customers to run sides inside a TYPO3
installation which is interesting for people who would like to offer some
kind of "namecards" for businesses and private sector. They would need the
possibility to select a Theme with the Theme switcher and then the content
and of course their headings will switch into the right positions.

Concerning Manpower you are a bit wrong right now as we do lots of
Processwire [http://processwire.com] meanwhile which offers much more speed
and much more flexibility than TYPO3, especially for multilingual and
multidomain sites or sites like mentioned but where you like to run the
sites from multiple single databases but from one core. Unfortunately lots
of customers have never heard about that new CMS before and want to stick
therefore to TYPO3 and this is where we for us and I guess also lots of
others which still continue working with TYPO3 would need THEMES which are
interchangeable including those headers.

Of course changing the existing Themes will break projects which have been
done before and therefore I also suggest simply to create a copy and make
an interchangeable branch for those templates and in future better stick to
the interchangeable stuff which is not a great deal as mentioned already.
(search and replace) Otherwise there will be lots of very similar looking
templates soon in TER only because of the different h1-h6 settings.

TYPO3 is not like Processwire very open for lots of additional Header
designs as it provides only a very limited number of possibilities in the
Layout Settings. This might need to be changed i future TYPO3 versions to
enable also more than only 7 Layout Settings as than there won't be those
problems like mentions.

And of course it is also a problem because the rendering is different and
orientated on those layout settings. which means if you have Layout 1 set
to h1 than Layout 1 gets rendered also on another template even there it is
set probably to h3 or something else.

I will see if i can work on a fork first and than you can see perhaps what
I mean.

Kay, you have a nice Template switcher for the frontend - Try to use that
one on the TYPO3-THEMES.org website in your demo, than you are actually
facing exactly the same problems I have just mentioned in that Thread. This
nice ThemeSwitcher is worthless if those header settings are not somehow
standardized, which means you have with TYPO3 Themes at the end the same
workload you would have in simply using any other TYPO3 Template (Theme) -
Moox, Flux, t3bootstrap, t3sbootstrap etc there are meanwhile a lot of them
- most done with Flux unfortunately.

But all of them are not interchangeable.

our goal here is to build up again something like the former WEC Starter
Package to encourage anybody to use TYPO3 and learn TYPO3 to "fly" even
they probably have no idea on how to get the engine started.

With kind regards,
Mit freundlichen Grüßen,
Con un cordial saludo,
Cordialement,
с сердечным приветом,
เรื่องที่เกี่ยวกับชนิด,
與親切的問候,

_ANDI BECKER_

CEO/General Manager LisAndi Co., Ltd.

_--------------------------------------------------_
_LisAndi Co. Ltd._, Phuket, Thailand (lisandi.com)
15/21 M.2 Viset Road, Rawai, Muang, Phuket, Thailand 83130

Mobile: +66 (0)81 606 3378
VoIP:   +49 (0)711 50 88788 50
Fax:     +49 (0)711 50 88788 50
Skype:          lisandi
Facebook:     andibecker
Google Talk:  andi@lisandi.com
Facetime:      andi@lisandi.com

---

This email may contain confidential and/or privileged information. If you
are not the intended recipient (or have received this email by mistake),
please notify the sender immediately and destroy this email. Any
unauthorized copying, disclosure or distribution of the material in this
email is strictly prohibited. Email transmission security and error-free
status cannot be guaranteed as information could be intercepted, corrupted,
destroyed, delayed, incomplete, or contain viruses. The sender therefore
does not accept liability for any errors or omissions in the contents of
this message which may arise as a result of email transmission

**Comment by kaystrobach** [comment] 2015-09-18 07:17
Typo3-themes.org is a flow application... No chance to get an extension running ...

Please open pull requests before forking ...

**Comment by kaystrobach** [comment] 2015-09-18 07:17
And you already can adjust the number of lazout options quite easily, the technology is called TSConfig :smile:

**Comment by lisandi** [comment] 2015-09-18 07:18
:-)
I meant the demo site for Themes!

With kind regards,
Mit freundlichen Grüßen,
Con un cordial saludo,
Cordialement,
с сердечным приветом,
เรื่องที่เกี่ยวกับชนิด,
與親切的問候,

_ANDI BECKER_

CEO/General Manager LisAndi Co., Ltd.

_--------------------------------------------------_
_LisAndi Co. Ltd._, Phuket, Thailand (lisandi.com)
15/21 M.2 Viset Road, Rawai, Muang, Phuket, Thailand 83130

Mobile: +66 (0)81 606 3378
VoIP:   +49 (0)711 50 88788 50
Fax:     +49 (0)711 50 88788 50
Skype:          lisandi
Facebook:     andibecker
Google Talk:  andi@lisandi.com
Facetime:      andi@lisandi.com

---

This email may contain confidential and/or privileged information. If you
are not the intended recipient (or have received this email by mistake),
please notify the sender immediately and destroy this email. Any
unauthorized copying, disclosure or distribution of the material in this
email is strictly prohibited. Email transmission security and error-free
status cannot be guaranteed as information could be intercepted, corrupted,
destroyed, delayed, incomplete, or contain viruses. The sender therefore
does not accept liability for any errors or omissions in the contents of
this message which may arise as a result of email transmission

**Comment by Bunnyfield** [comment] 2015-09-18 07:42
I will focus on the actual technical issue:

@lisandi You said: "TYPO3 is not like Processwire very open for lots of additional Header
designs as it provides only a very limited number of possibilities in the
Layout Settings. This might need to be changed i future TYPO3 versions to
enable also more than only 7 Layout Settings as than there won't be those
problems like mentions."

Well - tt_content has several fields that can be used for changing "layouts" and with THEMES installed the current settings for a 6.2 LTS environment regarding headers are:

Layout => VARCHAR 255
header_position => VARCHAR 6
header_layout => VARCHAR 30

and you can even add

tx_themes_behaviour, tx_themes_variants and tx_themes_responsive

since those are creating lots of combinations of CSS classes that might influence the frontend output  - and therefor the "layout" - of tt_content as well.

I don't know what makes you think, there would be a limit of seven header layouts, since on the one hand there is a technical limit due to the length of the field, but actually the number of possible combinations within a single field is already around billions, while the number of possible combinations of all those fields is close to unlimited. And you can add as many items to the TCA settings of a selectbox as you like to create lots of different variants to select from. 

Each header might still behave completely different though, depending on the selected generic CSS classes for its parent element. Same thing for almost any other selectable design, layout, behavior, whatever - Put a single element in another container and it will look and feel completely different without changing a single value of that particular element.

The only use case that might need stuff like that would be the "Theme Switcher" you are talking about, but actually this is not a must have but just one way of creating a show case for themes. When you take a look at Themeforest, Wrapbootstrap or other template selling sites, you will notice that they don't use the same content for each of their designs at all.

Most of the people who choose a theme for their site, will never switch a theme during one life cycle of that site, but they might do it for a relaunch, so they will usually have to adjust their content anyway.

So the logical structure in the backend you are talking about is a mere illusion. If you still think there should be something like that, feel free to do that with your own themes, but please don't upload stuff like theme_bootstrap_highland2 or better_theme_bootstrap_highland to the TER, since this will again lead us to the confused situation we actually wanted to avoid with THEMES.

Back 2 work now :-)

**Comment by lisandi** [comment] 2015-09-18 08:37
Hi Jo

Unfortunately there is no other way around than uploading the stuff to TER
as it is the central point for everyone to get the updates etc. Beside this
it would be useful to keep the naming as close as possible as it will be
actually the same Themes. So why not. It won't lad to confusion as people
who have the original highland installed will update of course that one and
the others which have a variation of highland will get the variation.

It is more a problem to maintain both templates as highland and highland
variation need to be maintained from 2 different places. But that is
feasible.

Thanks for explaning all those possibilities - but exactly because of those
great possibilities I really don't understand why the hell you stick so
close to the inhomogene Layout 1 - 5 and header 1 - 5 Settings which most
people will be using on their main sites.

"Most of the people who choose a theme for their site, will never switch a
theme during one life cycle of that site, but they might do it for a
relaunch, so they will usually have to adjust their content anyway."

In that case than there is also absolute no need for customers to use
THEMES if they get the same like i.e. Bootstrap Package already in Version
7 - a not interchangeable solution. So what is the goal? It looks like the
goal to provide something like the Framework for TemplaVoila provided to
customers is simply gone.

If Templates are Interchangeable there could be Template Developers
specialized on only doing those Templates and customers could buy them -
integrate them and finished without any need of any aditional developer who
has to adjust all the content to the new settings.

Thinks like highland - eastern, highland - christmas, highland - out of
school etc would be very easy to realize and mangeable. Those Template
designers not even would need to have TYPO3 knowhow to adjust the designs
and with a click on a per page base the template would be switchable and
the content would simply slide into the correct position and layout without
the need of aditional adjustments as long as it is concerning the major h1
to h4 settings and nothing else I am talking about!

With kind regards,
Mit freundlichen Grüßen,
Con un cordial saludo,
Cordialement,
с сердечным приветом,
เรื่องที่เกี่ยวกับชนิด,
與親切的問候,

_ANDI BECKER_

CEO/General Manager LisAndi Co., Ltd.

_--------------------------------------------------_
_LisAndi Co. Ltd._, Phuket, Thailand (lisandi.com)
15/21 M.2 Viset Road, Rawai, Muang, Phuket, Thailand 83130

Mobile: +66 (0)81 606 3378
VoIP:   +49 (0)711 50 88788 50
Fax:     +49 (0)711 50 88788 50
Skype:          lisandi
Facebook:     andibecker
Google Talk:  andi@lisandi.com
Facetime:      andi@lisandi.com

---

This email may contain confidential and/or privileged information. If you
are not the intended recipient (or have received this email by mistake),
please notify the sender immediately and destroy this email. Any
unauthorized copying, disclosure or distribution of the material in this
email is strictly prohibited. Email transmission security and error-free
status cannot be guaranteed as information could be intercepted, corrupted,
destroyed, delayed, incomplete, or contain viruses. The sender therefore
does not accept liability for any errors or omissions in the contents of
this message which may arise as a result of email transmission

**Comment by Bunnyfield** [comment] 2015-09-18 08:57
Nobody said we stick to anything. The point is, there are much more important things to do than moving around some header layouts to fit the use case of a template switcher, that might never happen in the near future.

These things would be:
1. Creating more themes based on DIFFERENT designs
2. Creating a set of THEMES extensions and themes that will be compatible to TYPO3 7 LTS
3. Introducing structured content to the core and making gridelements (and at the same time THEMES) compatible to that
4. Fixing bugs and include new features to both the 6.2 and the 7 compatible versions.

And so on and so forth ...

If you still prefer to focus on nitpicking and small details of already existing themes, you should stop complaining and discussing stuff to death and simply do what other people do, when they want something to be changed: Deliver code and make a pull request.

**Comment by lisandi** [comment] 2015-09-18 12:42
Don't be so angry Jo

we only made a useful suggestion and thats it. Before enhancing the mass
with more tempates and perhaps even more weird h1-h4 settings (this is our
point of view, yours might differ) we like to simple normalize some stuff
so that the templates which than get created with different designs are
simply switchable like those from Framework of TemplaVoila.

so step one would be to create a red line concerning those headers h1 - h4
which will be used in the demo content too.
-> right now there are some templates already on git and TER and with those
it would be useful to start to get things done.
-> after that is done we have a concept we than will follow while creating
variations of those templates for different purposes
-> 7 LTS would be nice but right now we concentrate on 6.2 as TemplaVoila
and its Framework for templaVoila is running good here and still needs
improvement in 7 LTS - to keep it simple we stick also with THEMES on the
LTS release cycle.
etc. p.p.

it is not at all nitpicking but simply a requirement we and I am sure also
others have who have multidomain sites i.e. from different churches or
institutions or schools and who are in need of switchable templates for
Themes as those customers are already used to the way this is handled in
Framework for TemplaVoila and we would like to switch them to THEMES to. We
don't complain we suggest, which makes a big difference and I am happy that
this disscussion lead at least to a clear statement "that might never
happen in the near future."

So we know we simply have to create a more or less duplicated set of all
those templates and the upcoming ones to make things happen for T3Pack
Packages which will need interchangeable Templates. Thanks - it saves a lot
of time!

With kind regards,
Mit freundlichen Grüßen,
Con un cordial saludo,
Cordialement,
с сердечным приветом,
เรื่องที่เกี่ยวกับชนิด,
與親切的問候,

_ANDI BECKER_

CEO/General Manager LisAndi Co., Ltd.

_--------------------------------------------------_
_LisAndi Co. Ltd._, Phuket, Thailand (lisandi.com)
15/21 M.2 Viset Road, Rawai, Muang, Phuket, Thailand 83130

Mobile: +66 (0)81 606 3378
VoIP:   +49 (0)711 50 88788 50
Fax:     +49 (0)711 50 88788 50
Skype:          lisandi
Facebook:     andibecker
Google Talk:  andi@lisandi.com
Facetime:      andi@lisandi.com

---

This email may contain confidential and/or privileged information. If you
are not the intended recipient (or have received this email by mistake),
please notify the sender immediately and destroy this email. Any
unauthorized copying, disclosure or distribution of the material in this
email is strictly prohibited. Email transmission security and error-free
status cannot be guaranteed as information could be intercepted, corrupted,
destroyed, delayed, incomplete, or contain viruses. The sender therefore
does not accept liability for any errors or omissions in the contents of
this message which may arise as a result of email transmission

**Comment by Bunnyfield** [comment] 2015-09-18 13:16
First of all, nobody is angry, just a bit sick of your lengthy discussions about stuff with minor priorities.
Since you tend to misunderstand things - some clarification:

1.) "the use case of a template switcher, that might never happen in the near future"
This has nothing to do with the header changes you proposed , but with exactly that "template switcher" - nobody needs that for the FRONTEND currently and it can already be done in the BACKEND,  so it might not happen in the near future.

2.) Please deliver code and make a pull request if you want something to change
If you think this is important, feel free to invest time into coding but stop discussing that much, since this has usually lead us nowhere as you might remember and the resources of the team are limited.

3.) Please don't waste time duplicating stuff, when following 2.) would be enough

4.) Please don't publish duplicated stuff to the TER when following 2.) would be enough - this would just lead to confusion of the users

5.) Please try to invest time in developing or finishing new themes instead, which will be MUCH more important for the TYPO3 community. - A good starting point could be theme_bootstrap_restart, which has a paid extended license already but has just been initially pushed to github recently.

Of course I can not prevent you from doing things the way you think they must be done, since it's all open source stuff. So I can just nicely ask you to stick to these points, so we will happily support your team.

It's up to you :-)

**Comment by Bunnyfield** [comment] 2015-09-18 13:30
Back to the original issue:

If I got it right, it is about Header labels and sorting of the headers in the dropdown box in the backend editing form. So we will need a pull request containing the TSconfig settings and some additional entries in the language file. As soon as those changes will be available we can check that and decide if and how it will be merged.

Since these will be breaking changes we will need at least some information for the users and maybe a kind of migration code as well.

**Comment by lisandi** [comment] 2015-09-18 13:32
Exactly that is what it is all about ! Thanks for understanding

All the rest is just fine IMHO!

have a nice evening!

With kind regards,
Mit freundlichen Grüßen,
Con un cordial saludo,
Cordialement,
с сердечным приветом,
เรื่องที่เกี่ยวกับชนิด,
與親切的問候,

_ANDI BECKER_

CEO/General Manager LisAndi Co., Ltd.

_--------------------------------------------------_
_LisAndi Co. Ltd._, Phuket, Thailand (lisandi.com)
15/21 M.2 Viset Road, Rawai, Muang, Phuket, Thailand 83130

Mobile: +66 (0)81 606 3378
VoIP:   +49 (0)711 50 88788 50
Fax:     +49 (0)711 50 88788 50
Skype:          lisandi
Facebook:     andibecker
Google Talk:  andi@lisandi.com
Facetime:      andi@lisandi.com

---

This email may contain confidential and/or privileged information. If you
are not the intended recipient (or have received this email by mistake),
please notify the sender immediately and destroy this email. Any
unauthorized copying, disclosure or distribution of the material in this
email is strictly prohibited. Email transmission security and error-free
status cannot be guaranteed as information could be intercepted, corrupted,
destroyed, delayed, incomplete, or contain viruses. The sender therefore
does not accept liability for any errors or omissions in the contents of
this message which may arise as a result of email transmission

**Comment by Bunnyfield** [comment] 2015-09-18 13:42
And another thing we should think about is, how to deal with a kind of fallback, since there might be lots of header layouts in theme A that might not be available in theme B. - Usually there is the "default" layout in the dropdown and a "default" setting in TypoScript for that purpose.

Since some page types of several themes already provide the h1 header within the page, the default header is set to h2 currently, which would mean, every selected header layout that  is not available, will be rendered as h2 instead.

Without any additional theme specific layouts and labels the list is:

0 = default = h2
1 = Layout 1 = h1
2 = Layout 2 = h2
3 = Layout 3 = h3
4 = Layout 4 = h4
5 = Layout 5 = h5
100 = Hidden = no header rendered at all

If i got you right, this should not be touched by any theme, since it will make sure, those values will always generate the same code regardless of the selected theme. So everything that adds more than a simple hx should be added to the list using other values, labels and output?

**Comment by lisandi** [comment] 2015-09-18 15:02
exactly Jo

unfortunately your settings and the settings from Mosaic are different

This is causing the design peoblems when Layout 1 = 1 in Highland but h3 in
Mosaic.

The idea in Mosaic is to give Editors some kind of easy workflow and could
end up in something like, but all Labels would need to be renamed to
something which will than appear in the same order and naming in all
templates.

Default = h2
Layout 1 = h3
Layout 2 = h3 variation
Layout 3 = h4
Layout 4 = h4 variation
Layout 5 = horizontal Line/Separator
...

while in Highland it actually makes things optical much easier and it is
much less adjustment for Template developers necessary because

default = h2
Layout 1 = h1
Layout 2 = h2 - this oucl already be a variation of h2
Layout 3 = h3
Layout 4 = h4
Layout 5 = horizontal line/Seperator
100 = Hidden

In Mosaic the layout Labels always need to be renamed while it is actually
in the settings like it is used in Highland not really necessay as people
will assume that layout will be h1 and Layout 4 will be h4.

The problem is only that only one of both possibilities shoudl be used but
than throughout all templates.

All other settings could be custom.
Usual Editors i.e. of Schools or Churches etc won't ever use those other
headers as they will be simply happy with what will be provided from Layout
1 to Layout 5

With kind regards,
Mit freundlichen Grüßen,
Con un cordial saludo,
Cordialement,
с сердечным приветом,
เรื่องที่เกี่ยวกับชนิด,
與親切的問候,

_ANDI BECKER_

CEO/General Manager LisAndi Co., Ltd.

_--------------------------------------------------_
_LisAndi Co. Ltd._, Phuket, Thailand (lisandi.com)
15/21 M.2 Viset Road, Rawai, Muang, Phuket, Thailand 83130

Mobile: +66 (0)81 606 3378
VoIP:   +49 (0)711 50 88788 50
Fax:     +49 (0)711 50 88788 50
Skype:          lisandi
Facebook:     andibecker
Google Talk:  andi@lisandi.com
Facetime:      andi@lisandi.com

---

This email may contain confidential and/or privileged information. If you
are not the intended recipient (or have received this email by mistake),
please notify the sender immediately and destroy this email. Any
unauthorized copying, disclosure or distribution of the material in this
email is strictly prohibited. Email transmission security and error-free
status cannot be guaranteed as information could be intercepted, corrupted,
destroyed, delayed, incomplete, or contain viruses. The sender therefore
does not accept liability for any errors or omissions in the contents of
this message which may arise as a result of email transmission

**Comment by Bunnyfield** [comment] 2015-09-18 15:16
So the actual problem is, that mosaic settings are just kind of lazy, since they just changed the labels of existing layouts instead of adding new stuff, while Highland added layouts with new values (6 and 7) and kept the rest of the layouts as is.

Since the mosaic approach is completely unpredictable for any other kind of theme, we should stick to the way it is done in Highland. - Still themes developers can remove any unused header layout from the default list, since those settings will fallback nicely to the default when a theme is switched.
They just have to make sure the layouts are removed from the TypoScript settings as well.

OK - so we need a pull request for mosaic then :-)

**Closed as completed by Bunnyfield** 2015-09-18 15:16 UTC

**Comment by lisandi** [comment] 2015-09-19 01:37
I agree YES! Good idea!

With kind regards,
Mit freundlichen Grüßen,
Con un cordial saludo,
Cordialement,
с сердечным приветом,
เรื่องที่เกี่ยวกับชนิด,
與親切的問候,

_ANDI BECKER_

CEO/General Manager LisAndi Co., Ltd.

_--------------------------------------------------_
_LisAndi Co. Ltd._, Phuket, Thailand (lisandi.com)
15/21 M.2 Viset Road, Rawai, Muang, Phuket, Thailand 83130

Mobile: +66 (0)81 606 3378
VoIP:   +49 (0)711 50 88788 50
Fax:     +49 (0)711 50 88788 50
Skype:          lisandi
Facebook:     andibecker
Google Talk:  andi@lisandi.com
Facetime:      andi@lisandi.com

---

This email may contain confidential and/or privileged information. If you
are not the intended recipient (or have received this email by mistake),
please notify the sender immediately and destroy this email. Any
unauthorized copying, disclosure or distribution of the material in this
email is strictly prohibited. Email transmission security and error-free
status cannot be guaranteed as information could be intercepted, corrupted,
destroyed, delayed, incomplete, or contain viruses. The sender therefore
does not accept liability for any errors or omissions in the contents of
this message which may arise as a result of email transmission

**Comment by kaystrobach** [comment] 2015-09-19 05:39
@lisandi will you make a PR in mosaic referring that issue here?

**Comment by lisandi** [comment] 2015-09-19 06:49
Let me change the settings first to what Jo just wrote to keep it even with all other and of course upcoming templates. I am just modifying it on the examples I have here.
